### ISSUE TITLE
Depreciated constant in HA 2025.1.0 breaks integration

### ISSUE THREAD

**Issue by johnwilson1969** [georgezhao2010/midea_ac_lan#634]
### HA core version

2025.1.0

### Intergration version

0.3.22

### Device type and model

Dehumidifier

### Used App

Home Assistant

### The description of problem

I have the same issue covered under the umbrella of "unable to start after update to 2025.1.0" but a different error message:

 Setup failed for custom integration 'midea_ac_lan': Unable to import component: cannot import name 'TIME_DAYS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py) 

This seems to be due to TIME_DAYS being depreciated - notes in the source code says:

"""Deprecated: please use UnitOfTime.DAYS."""

EDIT: These and **possibly others** are all used in the integration and have been decreciated to new constants

    TIME_DAYS
    TIME_HOURS
    TIME_MINUTES
    TIME_SECONDS

EDIT 2: Seems like all have been updated to new values with the exception of PERCENTAGE

### The logs

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 5:40:21 PM (1 occurrences)
Last logged: 5:40:21 PM

Setup failed for custom integration 'midea_ac_lan': Unable to import component: cannot import name 'TIME_DAYS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/midea_ac_lan/__init__.py", line 17, in <module>
    from .midea_devices import MIDEA_DEVICES
  File "/config/custom_components/midea_ac_lan/midea_devices.py", line 1, in <module>
    from homeassistant.const import (
    ...<12 lines>...
    )
ImportError: cannot import name 'TIME_DAYS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/midea_ac_lan/__init__.py", line 17, in <module>
    from .midea_devices import MIDEA_DEVICES
  File "/config/custom_components/midea_ac_lan/midea_devices.py", line 1, in <module>
    from homeassistant.const import (
    ...<12 lines>...
    )
ImportError: cannot import name 'TIME_DAYS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by pauloon** [comment]
I'm having the same here. Will be waiting for a fix.
Thanks for reporting.

**Comment by fangming828** [comment]
我这里也遇到了同样的问题。请大佬修复。
谢谢。

**Comment by jesterod** [comment]
Same issue had to downgrade HA core

**Comment by vergil-zhao** [comment]
Just submitted a fix PR, you can also replace all deprecated constants by yourself. Changes in the PR above.

**Comment by leonhuhn** [comment]
Your PR works like a charm, thanks :)

**Comment by pcmike** [comment]
Same, waiting for this update to go live

**Comment by superpower10** [comment]
So we wait for a HACS Midea update? Right?

**Comment by vergil-zhao** [comment]
> Same, waiting for this update to go live

> So we wait for a HACS Midea update? Right?

I suggest you checkout the fork of mine instead of waiting. Seems this repo's owner would never merge it.

**Comment by deenx** [comment]
same here after update HA 2025.1.0

**Comment by leonhuhn** [comment]
> So we wait for a HACS Midea update? Right?

i would suggest updating your local copy of the repo through a HA file editor. 

All necessary updates can be seen here: https://github.com/georgezhao2010/midea_ac_lan/pull/635/commits/3bd4cf10b7d76686fe195f99528cab1d06f9dbec

Just add the changes to your local files to: /homeassistant/custom_components/midea_ac_lan/... (and there are 3 python files to be changed)

I have a gut feeling that this PR will be unanswered for quite some time as the repos original maintainer seems to be absent


also you could use this guide -> https://github.com/georgezhao2010/midea_ac_lan/pull/635#issuecomment-2571260746

**Comment by mf76130** [comment]
just went through it to correct mine, seems there are these 2 not changed:
    CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
    CONCENTRATION_PARTS_PER_MILLION
    and cause an error.
Trying to figure out what to change them to.

Edit: In the meanwhile i just imported the files via terminal and now it doesn't care about these constants anymore!

thanks a lot for the work

**Comment by erikgieseler** [comment]
This reporistory is dead because the maintainer has not been available for a long time and no more pull requests are being merged. You should switch to https://github.com/wuwentao/midea_ac_lan.

**Comment by dougle03** [comment]
Mine is/was working just fine. How gave permission for the integration to be removed from HACS....?
Now I have a problem that I didn't have before.... Thanks.... FFS

![Image](https://github.com/user-attachments/assets/58b2dbfd-be8c-4f6f-859e-b93874917f2c)
