### ISSUE TITLE
Unable to import component: cannot import name 'TIME_DAYS' from 'homeassistant.const

### ISSUE THREAD

**Issue by einsminion** [georgezhao2010/midea_ac_lan#637]
### HA core version

2025.1.0

### Intergration version

0.3.22

### Device type and model

Kaisai

### Used App

HAS

### The description of problem

Setup failed for custom integration 'midea_ac_lan': Unable to import component: cannot import name 'TIME_DAYS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py) 

### The logs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/midea_ac_lan/__init__.py", line 17, in <module>
    from .midea_devices import MIDEA_DEVICES
  File "/config/custom_components/midea_ac_lan/midea_devices.py", line 1, in <module>
    from homeassistant.const import (
    ...<12 lines>...
    )
ImportError: cannot import name 'TIME_DAYS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/midea_ac_lan/__init__.py", line 17, in <module>
    from .midea_devices import MIDEA_DEVICES
  File "/config/custom_components/midea_ac_lan/midea_devices.py", line 1, in <module>
    from homeassistant.const import (
    ...<12 lines>...
    )
ImportError: cannot import name 'TIME_DAYS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by OriginalCREart** [comment]
same here, appears after upgrading to 2025.1.0

**Comment by j-lujanp** [comment]
and here. Right after upgrading to 2025.1 too

**Comment by dmriding** [comment]
+1 to this issue after upgrading to 2025.1

**Comment by OriginalCREart** [comment]
I have replaced the old one with this [https://github.com/wuwentao/midea_ac_lan](https://github.com/wuwentao/midea_ac_lan). For me everything back to work normally.

**Comment by j-lujanp** [comment]
Thanks! It worked for me too.

**Comment by MMachor** [comment]
Thank you!  Worked here as well!

**Comment by jtabet0010** [comment]
> I have replaced the old one with this https://github.com/wuwentao/midea_ac_lan. For me everything back to work normally.

Can somone please explain what needs to be replaced and how , please...

**Comment by erikgieseler** [comment]
https://github.com/wuwentao/midea_ac_lan?tab=readme-ov-file#upgrade-from-georgezhao2010midea_ac_lan

**Comment by loeiks** [comment]
https://github.com/wuwentao/midea_ac_lan

Use this instead.
