### ISSUE TITLE
Integration error after update HA to 2025.6.0

### ISSUE THREAD

**Issue by booroondook-eng** [georgezhao2010/midea_ac_lan#656]
### HA core version

2025.6.0

### Intergration version

0.3.22

### Device type and model

Midea Refrigerator

### Used App

SmartHome

### The description of problem

Integration does not work after update HA to 2025.6.0

### The logs
```
2025-06-12 10:58:12.598 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Refrigerator for midea_ac_lan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/__init__.py", line 171, in async_setup_entry
    hass.async_create_task(hass.config_entries.async_forward_entry_setup(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

```

_No response_

**Comment by erikgieseler** [comment]
This reporistory is dead because the maintainer has not been available for a long time and no more pull requests are being merged. You should switch to https://github.com/wuwentao/midea_ac_lan.

**Comment by booroondook-eng** [comment]
> This reporistory is dead because the maintainer has not been available for a long time and no more pull requests are being merged. You should switch to https://github.com/wuwentao/midea_ac_lan.

Thanks for your information!
